runtime: go
api_version: go1
service: app-serving-prices

handlers:
# [START static_handlers]
# If the path is empty, show static index.html file
- url: /
  static_files: index.html
  upload: index.html

# Otherwise, find file in static directory
- url: /static
  static_dir: static
# [END static_handlers]

- url: /.*
  script: _go_app
#network:
#  instance_tag: priceservig
#  name: flex-app-asynch
#  subnetwork_name: app-engine-nodes
